### PR TITLE
Default Template Provider + RDXHD Provider

### PR DESCRIPTION
**Pull request by dali546**
In these commits I have done the following:
- Have added JSDocs in more than a few places
- Renamed variables to suit WebSocket
- simplified some logic and redundant passing of variables
- created a Default.js file and accompanied Test.js file to display how to use Default class (will change to be more robust)
- updated `resolve.js` to switch-case format to remove `uri.includes` and made it slightly simple.
- moved createEvent to the bottom of try-catch as it only needs to be executed once per resolve request
- a few other minor changes...

### CODE REVIEW

**Comment by SpajicM** [comment]
-1, regardless of changes made, the commits are a mess.

Let's say they should be organized same way you did the notes in description

1) Updated <filename> is non-descriptive.
2) Some commits have exact same name althrough they are not the same - if you've commited and did some related changes afterwards, you should amend the commits (git amend command)
3) .gitignore changes should not be commited
4) Merge remote upstream/master should be avoided by rebaseing instead of merging before creating a PR.

I'll leave the changes for devs to review.
I'm only writing this comment to make you aware that even if your contribution is valid and appreciated, commit history like this won't fly and PR can't be merged.

**Comment by NBTX** [comment]
I don't think I could've worded it better than @SpajicM myself.

I'll just reiterate though, to make sure it's clear; your work is appreciated and from what I can see the overall work is acceptable but your git commit history is mess.

You need to clean up the commits before we can properly consider merging this PR.

**Comment by FlyPigsFly** [comment]
I'm learning JavaScript right now so I'm in no way an expert. I also don't want you to take this personal but for me I couldn't merge this request. There's a lot of questionable changes. 

For instance https://github.com/dali546/Claws/blob/31dd9dfa35e9cf50161ec4abec09a1337a043ef1/src/scrapers/providers/Tutorial.md

> So far, this defines the main function, and exports it to the modules (no idea). `req` passes the request query data, and `sse` controls something.

I'm lost.

https://github.com/dali546/Claws/blob/31dd9dfa35e9cf50161ec4abec09a1337a043ef1/src/scrapers/providers/img-1.png

Is just a screen shot

src/scrapers/providers/movies/default.js

A much cleaner object oriented default provider was provided by @j0j00 in his pull request

.gitignore adds duplicate entries as well as what @SpajicM said

https://github.com/ApolloTVofficial/Claws/blob/d40225d27932c952f58f6184b8350f320104464b/src/scrapers/providers/index.js

Is reverting to older less cleaner code.

**Comment by dali546** [comment]
Sorry new to actual github...

**Pull request closed without merging**
