### PR TITLE
Add PrimeWire Provider

### PR DESCRIPTION
**Pull request by Teekzilla**
Just want to note one thing here. The provider seems to be getting the links properly. If you comment out the `resolvePromises.push()` and log `hostLink` at the end of the provider, you'll see that the provider is retrieving all the links fine.

I believe however, the errors that get logged are coming from resolvers themselves. Some resolvers don't have a check for if a file is there or not, thus any of those errors are caught with the latest `try-catch` changes. If you'd like to test and confirm that it's the resolvers, Spider-Man: Into the Spider-Verse is what I was testing against.

This also brings to light the fact that these resolvers should probably be updated to handle a check for the file. Also, as far as catching errors, I think adding a check and simplifying the error message to something like `Resolver: File Not Found` would be better.

**This cannot be merged until Kamino passes IMDB ID in it's query to Claws. Thus ApolloTVofficial/kamino#158 needs to be addressed before merging!**

### CODE REVIEW

**Comment by SpajicM** [comment]
Lack of resolver's error handling is the reason we've added try catch. It's a dirty but quick workaround to avoid Claws hanging/freezing. Proper solution would require all resolvers to be refactored to use BaseResolver, and that's a lot of work. If it's something you want to do, please go ahead. :)

So does this provider have a (working) resolver that would give us links in the end?

**Comment by kevincosmos** [comment]
I have tested this and am not getting any links from this provider.

Search example: Friends S02E02
0 scrape 0 result
Provider website has at least 3 valid links that we should be getting (openload)

**Comment by Teekzilla** [comment]
There should working links. Possible reason why is maybe the Openload resolver itself handles embed links. The links from PrimeWire seem to be linked to a file that you can download. So I'm not sure if that's why it's not resolving. But will look into it.

**Comment by Teekzilla** [comment]
For some reason, `resolveWithFullResponse` doesn't seem to work as an option in `request-promise`. It works on mine, however on other people's system it doesn't seem to work. The problem was targeted though no clear solution or explanation as to why has been determined yet.

Thus, will be closing this PR for now and focusing on other work.

**Pull request closed without merging**
