### PR TITLE
feat(provider) add Series9 universal provider

### PR DESCRIPTION
**Pull request by Teekzilla**
Added Series9 as a new universal provider. Everything is pretty straight forward, I'll add the `testing required` tag for now as well as request a review.

### CODE REVIEW

**Comment by kevincosmos** [comment]
Movies - Works (movies with ' in title also work)
TV Shows - Works with a caveat
   - Search for Westworld S2E1 and it finds 3 RapidVideo links. It should only find 1, instead it's finding all 3 rapidvideo links which are for different episodes
https://www2.series9.io/film/westworld-season-2/watching.html?ep=1

Below is image of what episodes it's finding:

**Comment by kevincosmos** [comment]
Ignore previous caveat, we have now introduces splitting rapidvideo links into one link for each quality (480p, 720p etc) where applicable, so the same episode has 3 links.

Ongoing discussion about how to pass the quality for these links - once resolved this is ready for merge.

**Comment by Teekzilla** [comment]
The quality for links is a separate topic related only to the RapidVideo resolver. It's out of the scope of this PR, I'll open another one when finished working on that.

**Comment by kevincosmos** [comment]
Thanks for clarification, this is ready for merge pending code review by @ddivad

**Pull request merged**
