### PR TITLE
Update Quality Utility Function

### PR DESCRIPTION
**Pull request by Teekzilla**
### Main Changes
- Updated the quality utility function to return integer values as noted in #121 
- Now uses regex to check for the quality instead of string comparisons

### Other Changes
- Added a method called `getNumericValue`to convert quality as a string to it's representative numeric value
- Updated RapidVideo to use `getNumericValue`
- Updated XStreamCDN to use `getNumericValue`
- AZMovies provider retrieves quality from the video page

### Notes
This should not be pushed to the server until Kamino implements the conversion from integers to strings for quality, as it seems to drop sources if quality is an integer...

### CODE REVIEW

**Comment by Teekzilla** [comment]
Sure, will update!

**Comment by FlyPigsFly** [comment]
Probably should pass the i flag too for case insensitivity

**Comment by Teekzilla** [comment]
> Probably should pass the i flag too for case insensitivity

The variable `filename` is set to lowercase at the beginning of the function so don't believe that's necessary.

**Comment by FlyPigsFly** [comment]
Right you are. So I guess that means A-Z would be redundant than

**Comment by Teekzilla** [comment]
> Right you are. So I guess that means A-Z would be redundant than

Ah you are right - will update!

**Pull request merged**
