### PR TITLE
Add TwoDDL Provider (RD-Universal)

### PR DESCRIPTION
**Pull request by Teekzilla**
### Changes
- Add TwoDDL as a universal, RD-only provider

### Notes
The time has finally come for RD specific providers. This is a universal provider, though their TV listing don't seem to be too vast. The way I set this up was to just wrap the scrape function with `if (hasRD) {...}` to only search based off whether the user has RD connected or not.

### CODE REVIEW

**Comment by ddivad** [comment]
@Teekzilla For RD specific providers can we make a new section in the index, so instead of having in `universal` and then having `hasRD` in the provider, in `resolveLinks` you can add the `RD` providers to `availableProviders` if `hasRD` is true.

Seems like it might be another approach, what do you think?

**Comment by kevincosmos** [comment]
> @Teekzilla For RD specific providers can we make a new section in the array (Eg: rd). Then, instead of having RD providers in `universal` and then having `hasRD` in the provider, in `resolveLinks` you can add the `rd` list of providers to `availableProviders` if `hasRD` is true.
> 
> Eg:
> 
> ```
> tv: [
> 
> ],
> universal: [
> 
> ],
> rd: [
>      'TwoDDL'
> ]
> ```

Forgive me if I'm not understanding this fully, but I don't think I'm fully on board with this suggestion. Not all RD providers are going to be universal - so there will be instances of us scraping providers for TV shows when they may not even support it.

@ddivad

**Comment by kevincosmos** [comment]
I've had to fail the functional testing for this:
- TV shows don't seem to work (tried Cobra Kai S02, MasterChef Junior S07E08 - both of which are listed on the provider)

I'd also like further discussion about how we are handling RD providers - generally speaking a film/show can have multiple search results because they tend to be split by release group - see the below example where "Miss Bala" has 3 correct results pages because there are three release group releases: https://bit.ly/2VujjXf

**Comment by Teekzilla** [comment]
> TV shows don't seem to work (tried Cobra Kai S02, MasterChef Junior S07E08 - both of which are listed on the provider)

Nice find, I am working on expanding the search as those shows seem to display as full seasons and not by episode. Will update **Soon™**.

> I'd also like further discussion about how we are handling RD providers - generally speaking a film/show can have multiple search results because they tend to be split by release group - see the below example where "Miss Bala" has 3 correct results pages because there are three release group releases: https://bit.ly/2VujjXf

This has already been handled.

**Comment by Teekzilla** [comment]
Just updated. It now takes into account search based on season if searching by episode fails. The pattern being matched is no longer `SXXEXX` pattern. S02E01 is designated as `.201.` in these cases. This is being left as this for now as we cannot find any exceptions or other patterns. If these are found down the line, this provider will be updated!

**Comment by kevincosmos** [comment]
> Just updated. It now takes into account search based on season if searching by episode fails. The pattern being matched is no longer `SXXEXX` pattern. S02E01 is designated as `.201.` in these cases. This is being left as this for now as we cannot find any exceptions or other patterns. If these are found down the line, this provider will be updated!

I have tested a show with the "201" style formatting (Cobra Kai) and can confirm I now get the links.
I have marked this as "under discussion" pending conversation around a film that I should be able to find but can't.

**Pull request merged**
