### PR TITLE
Add SolarMovie Provider (Squash Merge)

### PR DESCRIPTION
**Pull request by Teekzilla**
- This depends on ApolloTVofficial/kamino#123 being merged. This implementation assumes that the year is passed as a separate parameter and not with the title itself.
- The site sends back a lot of links especially for movies. Even though Claws serves links asynchronously, Kamino does not handle them that way. This means for long lists of sources there will be quite a wait. Thus probably should not merge this until Kamino handles the links asynchronously as well.

### CODE REVIEW

**Comment by SpajicM** [comment]
Looks good, but I'd squash/merge those 4 commits into one "Add SolarMovie universal provider" since, reading the github history it wouldn't be clear what are they refering to

**Comment by kevincosmos** [comment]
This also can't be merged until we start displaying links as they are resolved - I spent about 3 minutes waiting on the server resolving over 300 links for one movie.

I'm not sure if this website takes its content and continuously uploads it to OpenLoad? The same file with the same file name appears 300+ times for Boy Erased and Spider-Verse. Should we implement a limit of "20 films with the same title provided by the same resolver" or something along those lines?

**Comment by SpajicM** [comment]
@kevincosmos 

As usual, here we've some easy but not ideal solution, or harder but more complete solution:

- Cutting off a resolver at a certain number, makes absolutely no sense, for example, most of our providers use OpenLoad, cutting Openload at for example 10 makes a bunch of providers useless.
- Maybe @Teekzilla's original solution is not so bad - if all files are reupload mirrors, let's take last 5 from SolarMovie, and be done.
- Detecting duplicates based on same filename, same size, or even more "strict", same file hash (if file is 100% identical) all could be done on Kamino side, but that won't really help with anything. The wait time would be the same, you would just see less results in the end, and Claws would still work resolving links that in the end you won't get.
- More concrete solution for this would be to extend Claws functionality and make it more aware of what results it already resolved, from which provider they're received, what filename/size/hash are the files that it resolved, etc. This would also help with showing more descriptive loading progress in Kamino.

Tagging boss @NBTX to make the call :)

**Comment by ddivad** [comment]
In relation to @SpajicM's comment here:

I like option 4, which would be to add functionality to the resolvers to track what files have been resolved, and if they have been seen by that resolver or not before. I think it should be a combination of `Provider - Resolver - Filename` so that the same file can come from 2 providers, but a provider can't send 2 of the same files to Kamino. This would be better, as sometimes the same file can come from 2 providers, but each provider might have different latencies, and for the user, some providers can be isp blocked.

The piece that I think we should ignore for now is "showing more descriptive loading progress in Kamino", as discussed in Discord as this seems kind of impossible, given how the providers work. TLDR: We can count the number of links we have already resolved, but have no way to know how many links we will find. So there is no way to say "4 out of 15 links", because there is no real way to get that "15" piece.

For the tracking in the resolvers, we might be able to do the following:

- Make the resolvers be classes (similar to the new provider structure).
- Have an array as a class variable to keep track of the files that resolver has already seen / resolved. That array would have something like `[provider, filename, filesize, (maybe) hash]`.
- When resolving, only add something that has never been seen before and then return that to kamino .

This would require a lot of rework, but could be a clean way to implement this.

Thoughts? @claws-dev @NBTX

**Comment by SpajicM** [comment]
I agree with @ddivad's way of implementation.
One could argue it's up to client to filter the results it got, but I view the server as the central point of logic for serving links, and think all work related to it should be done there, benefit being easier to change and extend logic without updating all clients, and therefore avoiding different results across different client platforms or app versions.

**Comment by Teekzilla** [comment]
Just to clarify that last commit. 5Movies has the same structure as SolarMovie so removed the provider and reference. The issue however is the 5Movies takes way too long to load. So it never passes the timeout. Thus, made a comment about it in case the reliability of the site changes in the future.

Yeah definitely should squash merge these.

**Comment by ddivad** [comment]
What's happening with this PR @Teekzilla ? Is it still being worked on, and has it been tested with the recent duplicate filtering that was implemented in Claws? Would be good to get it tested and merged as its been here for a while :)

**Comment by SpajicM** [comment]
@ddivad  as far as I remember this provider has a bunch of mirrors, but each mirror is a different URL, meaning it would bypass our "duplicate filtering" and add 100 links of same movie?

**Comment by kevincosmos** [comment]
> @ddivad as far as I remember this provider has a bunch of mirrors, but each mirror is a different URL, meaning it would bypass our "duplicate filtering" and add 100 links of same movie?

That is correct

**Comment by Teekzilla** [comment]
Yeah I can update the PR to be on par with the latest. I haven't tried since all the recent changes. I will try and clean up all my PRs today. But yeah that's taking into account that there are technically duplicates in the sense that the same file is uploaded to multiple hosts or multiple times. That I don't think would get filtered out.

**Comment by Teekzilla** [comment]
Just want to update this. The final decision on this is was to pick out up to 5 links for each resolver on a page. The follow changes should do just that. Hopefully, we can do some testing tomorrow and merge this.

Also I had removed 5Movies as a clone before. However, I added 5Movies back as a clone to this as their site seems to be stable now.

Would appreciate some testing/breaking! :wink: @ddivad @SpajicM @kevincosmos

**Comment by SpajicM** [comment]
Tested and ready to go!

**Pull request merged**
