### PR TITLE
Add DLFilm Provider (Squash Merge)

### PR DESCRIPTION
**Pull request by Teekzilla**
This provides streamable direct download links. As discussed on Discord there are two things that still need to be done to allow these to be used in Kamino.

1. Kamino need to be updated to allow direct links. Claws should filter whether they can be streamed.
2. Claws needs to have a feature to do HEAD requests on direct links and check whether they can be streamed and only send them to Kamino if true.

Another point of discussion is how to handle the resolving of direct links. We could follow the same pattern or create a single resolver for all direct links.

### CODE REVIEW

**Comment by SpajicM** [comment]
Tested, working 👍

**Comment by ddivad** [comment]
Seems you have conflicts to fix here before I can merge @Teekzilla

**Comment by Teekzilla** [comment]
Should be good to go! @ddivad

**Comment by ddivad** [comment]
Thanks @Teekzilla

**Pull request merged**
