### PR TITLE
Added MovieMax Provider & Resolver

### PR DESCRIPTION
**Pull request by Teekzilla**
1. Added MovieMax provider.
2. Added a direct-download-type resolver for MovieMax.

This can be merged as is but leaving a note that DibaMoviez uses the same server as this. Thus whichever one of the providers get merged second will need to resolve conflicts in `resolve.html`.

### CODE REVIEW

**Comment by kevincosmos** [comment]
Client changes to hide dubbed links

**Comment by Teekzilla** [comment]
> Client changes to hide dubbed links needed

I actually want to get input on this. Should the client handle it or should it be filtered out at the provider itself? @kevincosmos @ddivad @SpajicM 

> Titles with a ' in the title do not work

Not sure if this is relevant to the PR, as the site itself is missing apostrophes. Though I'll also throw this out there, should that be handled at the provider or not? I personally was thinking no just because I don't think we should be responsible for mistakes such as that. However, I do also see value if a search should be done with apostrophes stripped form titles, as this would apply to a lot of movies.

**Comment by kevincosmos** [comment]
> > Client changes to hide dubbed links needed
> 
> I actually want to get input on this. Should the client handle it or should it be filtered out at the provider itself? @kevincosmos @ddivad @SpajicM
> 
> > Titles with a ' in the title do not work
> 
> Not sure if this is relevant to the PR, as the site itself is missing apostrophes. Though I'll also throw this out there, should that be handled at the provider or not? I personally was thinking no just because I don't think we should be responsible for mistakes such as that. However, I do also see value if a search should be done with apostrophes stripped form titles, as this would apply to a lot of movies.

Thanks for the feedback:

I have no idea what I meant by "client changes", I think I meant that the provider itself needs to be changed to get rid of dubbed links, or we need to regex the file or some other method to identify that it's dubbed content (otherwise I will try to play something, and it will give me dubbed content and I won't know in advance).

Regarding the apostrophe, I don't know how this should be handled.

Generally speaking, I comment on the things that I find without the knowledge of how/where/if it should be fixed, as I don't have the technical knowledge of this type of stuff - so things I may pick up on are not always going to be directly related to the code in your PR, it may in fact be an issue with the actual provider - But I feel this is the best place to give my feedback on it so it can be documented and addressed correctly if needed.

**Comment by Teekzilla** [comment]
Closing for now because of captcha. They point to the same directories as DibaMoviez. Thus, it can be reopened once there is progress on that.

**Pull request closed without merging**
